### ISSUE TITLE
Useless "InternalError" with no message when attempting to provision on an account with no SSH keys

### ISSUE THREAD

**Issue by arekinath** [joyent/sdc-cloudapi#2]
* Make a new account, with no SSH keys added
 * Create a sub-user on that account, give it administrator role, add SSH keys to it only
 * Use that sub-user to try to create a VM on the account (eg using sdc-createmachine)

Result:

```
sdc-createmachine: error (InternalError): Internal Error
```

In the logs on the cloudapi0 zone:

```
[2015-02-25T04:22:09.648Z] ERROR: cloudapi/30434 on 6e774737-6cbf-44d6-acb8-35a707866eac: unexpected error (req_id=dd459c70-bca5-11e4-8533-0d6eb058ec29)
    AssertionError: options (object) is required
        at KeyRequiredError.RestError (/opt/smartdc/cloudapi/node_modules/restify/lib/errors/rest_error.js:40:16)
        at new KeyRequiredError (/opt/smartdc/cloudapi/lib/machines.js:62:15)
        at /opt/smartdc/cloudapi/lib/machines.js:805:25
        at /opt/smartdc/cloudapi/node_modules/ufds/node_modules/once/once.js:17:15
        at /opt/smartdc/cloudapi/node_modules/ufds/node_modules/once/once.js:17:15
        at EventEmitter.<anonymous> (/opt/smartdc/cloudapi/node_modules/ufds/lib/index.js:2787:13)
        at EventEmitter.emit (events.js:95:17)
        at _done (/opt/smartdc/cloudapi/node_modules/ufds/node_modules/ldapjs/lib/client/client.js:1133:22)
        at messageCallback (/opt/smartdc/cloudapi/node_modules/ufds/node_modules/ldapjs/lib/client/client.js:1219:16)
        at Parser.onMessage (/opt/smartdc/cloudapi/node_modules/ufds/node_modules/ldapjs/lib/client/client.js:833:14)
```

It looks like the API for `RestError` in restify has changed and now requires an `options` object instead of the arguments that `machines.js` is giving it. As a result, the useful error message `'At least one SSH key is required to provision'` which it's supposed to produce in this case, is being turned into a useless `'Internal Error'`.

As an aside, I think `loadSSHKeys` should be looking at sub-users as well as the account keys, perhaps with a second special role "login" or a policy addition. This also needs to be fixed with smartlogin though, which currently ignores sub-users and roles/policy too.

**Comment by kusor** [comment]
Thanks for the fix for the Restify issue. It is not on the immediate plans to add smart login support for sub-users. Regarding `loadSSHKeys` if we load the sub-user keys as `account` keys, those would be operating as the `account` owner, which is exactly what we're trying to avoid with the addition of sub-users, though.
