### ISSUE TITLE
Could not discover service endpoint for DOCKER_HOST from CloudAPI

### ISSUE THREAD

**Issue by agdg** [joyent/sdc-cloudapi#6]
Hi, I am testing triton. I have this infrastructure: headnode, node05 and node07. I can log on to the "operations portal" and create new virtual machines. I tried to create VM with the following technologies: KVM, LX and joyent.

However I can not connect via CloudAPI (docker), when i trying to install I get the following error:
```
[root@devitop ~]# ./sdc-docker-setup.sh -k 192.168.2.4 webmin /root/.ssh/id_rsa
Setting up Docker client for SDC using:
    CloudAPI:        https://192.168.2.4
    Account:         webmin
    Key:             /root/.ssh/id_rsa

If you have a pass phrase on your key, the openssl command will
prompt you for your pass phrase now and again later.

Verifying CloudAPI access.
CloudAPI access verified.

Generating client certificate from SSH private key.
Wrote certificate files to /root/.sdc/docker/webmin

Get Docker host endpoint from cloudapi.
sdc-docker-setup.sh: warn: could not get Docker service endpoint from CloudAPI (no docker service listed)
Could not discover service endpoint for DOCKER_HOST from CloudAPI.
```

When I execute the command sdc-healthcheck in headnode, it tells me that everything is fine. However when I execute sdc-listdatacenter in cloudapi0 I get the following error:

```
[root@d841f209-c3f7-4cd3-b79f-8690c6541d22 (MAD-CPD0:cloudapi0) ~/.ssh]# sdc-listdatacenters --account admin --url https://192.168.2.4 --keyId $( ssh-keygen -lf /root/.ssh/sdc.id_rsa | awk 'BEGIN {FS=" "}; {print $2}') -k

/opt/smartdc/cloudapi/node_modules/smartdc/lib/cloudapi.js:3018
            throw (err);
                   ^
Error: true not found in: /root/.ssh
    at _checkPublic (/opt/smartdc/cloudapi/node_modules/smartdc/node_modules/smartdc-auth/lib/index.js:89:23)
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)
[root@d841f209-c3f7-4cd3-b79f-8690c6541d22 (MAD-CPD0:cloudapi0) ~/.ssh]#
```

Services that are running in cloudapi0:
```
[root@d841f209-c3f7-4cd3-b79f-8690c6541d22 (MAD-CPD0:cloudapi0) ~/.ssh]# svcs -a
STATE          STIME    FMRI
legacy_run     Sep_28   lrc:/etc/rc2_d/S99net_tune
disabled       Sep_28   svc:/system/manifest-import:default
disabled       Sep_28   svc:/system/identity:domain
disabled       Sep_28   svc:/system/early-manifest-import:default
online         Sep_28   svc:/system/svc/restarter:default
online         Sep_28   svc:/network/datalink-management:default
online         Sep_28   svc:/network/ip-interface-management:default
online         Sep_28   svc:/system/filesystem/root:default
online         Sep_28   svc:/network/loopback:default
online         Sep_28   svc:/system/boot-archive:default
online         Sep_28   svc:/system/filesystem/usr:default
online         Sep_28   svc:/system/device/local:default
online         Sep_28   svc:/system/filesystem/smartdc:default
online         Sep_28   svc:/milestone/devices:default
online         Sep_28   svc:/system/filesystem/minimal:default
online         Sep_28   svc:/system/name-service-cache:default
online         Sep_28   svc:/smartdc/mdata:fetch
online         Sep_28   svc:/network/physical:default
online         Sep_28   svc:/network/routing-setup:default
online         Sep_28   svc:/milestone/network:default
online         Sep_28   svc:/network/initial:default
online         Sep_28   svc:/network/service:default
online         Sep_28   svc:/network/dns/client:default
online         Sep_28   svc:/milestone/name-services:default
online         Sep_28   svc:/system/identity:node
online         Sep_28   svc:/milestone/single-user:default
online         Sep_28   svc:/milestone/sysconfig:default
online         Sep_28   svc:/network/netmask:default
online         Sep_28   svc:/system/filesystem/local:default
online         Sep_28   svc:/smartdc/agent/amon-agent:default
online         Sep_28   svc:/system/system-log:default
online         Sep_28   svc:/system/cron:default
online         Sep_28   svc:/milestone/multi-user:default
online         Sep_28   svc:/milestone/multi-user-server:default
online         Sep_28   svc:/smartdc/mdata:execute
online         Sep_28   svc:/smartdc/application/cloudapi:cloudapi-8084
online         Sep_28   svc:/smartdc/application/cloudapi:cloudapi-8081
online         Sep_28   svc:/smartdc/application/cloudapi:cloudapi-8083
online         Sep_28   svc:/smartdc/application/cloudapi:cloudapi-8082
online         Sep_28   svc:/cloudapi/haproxy:default
online         Sep_28   svc:/pkgsrc/stud:default
online         Sep_28   svc:/smartdc/application/config-agent:default
online         Sep_28   svc:/manta/application/registrar:default
```
Does this problem is due to a bug? or have I to configure something for CloudAPI?

**Comment by agdg** [comment]
This ticket can be closed. The problem was that I forgot to create the docker0 zone. Now everything works fine.

I think the SDC-listdatacenters ... command should check availability docker0 zone and show a descriptive error.

**Comment by kusor** [comment]
Ok, thanks!
