### ISSUE TITLE
Malformed user-agent breaks prometheus parser

### ISSUE THREAD

**Issue by teutat3s** [joyent/sdc-cloudapi#75]
While debugging why `triton-prometheus` stated that `cloudapi0` was DOWN, with the error: `expected equal, got "INVALID"`
I noticed a funny user-agent in a malicious POST attempt to cloudapi.
```
[2021-02-05T23:25:37.426Z]  INFO: cloudapi/audit/97818 on 5d980efc-cd02-4690-a871-5d8b050ec7da: handled: 401 (req_id=7c69147f-c657-4006-a50b-3b698890cb15, audit=true, remoteAddress=172.105.13.165, remotePort=33315, latency=10, route=updateaccount, _audit=true)
    POST /sdk HTTP/1.1
    content-length: 441
    user-agent: "Mozilla/5.0
    host: xx.xx.xx.xx
    x-forwarded-for: 172.105.13.165
    --
    HTTP/1.1 401 Unauthorized
    content-type: application/json
    content-length: 94
    access-control-allow-origin: *
    access-control-allow-headers: Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, Api-Version, Response-Time
    access-control-allow-methods: GET, HEAD, POST, PUT
    access-control-expose-headers: Api-Version, Request-Id, Response-Time
    connection: Keep-Alive
    content-md5: ZHr/q0kH6ganClU5iLN5zA==
    date: Fri, 05 Feb 2021 23:25:37 GMT
    server: cloudapi/9.14.0
    api-version: 9.0.0
    request-id: 7c69147f-c657-4006-a50b-3b698890cb15
    response-time: 10
    --
    InvalidCredentialsError: You must make authenticated requests to use CloudAPI
        at Server.assertAuthenticated (/opt/smartdc/cloudapi/lib/auth.js:404:21)
        at next (/opt/smartdc/cloudapi/node_modules/restify/lib/server.js:912:30)
        at f (/opt/smartdc/cloudapi/node_modules/once/once.js:25:25)
        at Server.tokenAuth (/opt/smartdc/cloudapi/lib/auth.js:305:16)
        at next (/opt/smartdc/cloudapi/node_modules/restify/lib/server.js:912:30)
        at f (/opt/smartdc/cloudapi/node_modules/once/once.js:25:25)
        at Server.signatureAuth (/opt/smartdc/cloudapi/lib/auth.js:133:16)
        at next (/opt/smartdc/cloudapi/node_modules/restify/lib/server.js:912:30)
        at f (/opt/smartdc/cloudapi/node_modules/once/once.js:25:25)
        at Server.preSignedUrl (/opt/smartdc/cloudapi/lib/auth.js:729:9)
    --
    req.timers: {
      "parseAccept": 195,
      "parseAuthorization": 24,
      "parseDate": 44,
      "bunyan": 137,
      "parseQueryString": 40,
      "readBody": 779,
      "parseBody": 136,
      "restifyResponseHeaders": 49,
      "xForwardedFor": 46,
      "setupSDCProxies": 116,
      "accountMgmt": 232,
      "preSignedUrl": 88,
      "signatureAuth": 26,
      "tokenAuth": 23,
      "assertAuthenticated": 1985
    }
```
Take note of:
`    user-agent: "Mozilla/5.0`

Using `promtool check metrics` on the cloudapi cmon endpoint brought up this 
```
error while linting: text format parsing error in line 1241: unexpected end of label value %!q(*string=0xc00045fa60)
```
and gave me the line to look for, where I noticed the user agent with an extra `"`, thats probably causing the prometheus parser error:

```
http_requests_completed{route="updateaccount",method="POST",user_agent=""Mozilla/5.0",status_code="401",datacenter="dc-1",instance="5d980efc-cd02-4690-a871-5d8b050ec7da",port="8081",server="ccfd1804-307b-11df-a234-e41f13425a34",service="cloudapi"} 1
```

**Comment by bahamat** [comment]
As it turns out, we appear to have run into this before: joyent/node-artedi#16.
